[workspace]

resolver = "2"

members = [
    "crates/artist",
    "crates/assistant",
    "crates/pl011-driver",
    "crates/uart-interface-types",
    "crates/ethernet-interface-types",
    "crates/eth-driver",
]
